version: '3.3'
services:
  postgres:
    image: postgres
    user: "root:root"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=12345
    ports:
      - "5432:5432"
#  pgadmin:
#    image: dpage/pgadmin4
#    user: "root:root"
#    container_name: pgadmin4_container
#    restart: always
#    ports:
#      - "8888:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: info@lambdaloopers.com
#      PGADMIN_DEFAULT_PASSWORD: 12345
#    volumes:
#      - ./data/pgadmin:/var/lib/pgadmin
#  zookeeper:
#    image: docker.io/bitnami/zookeeper:3.8
#    user: "root:root"
#    restart: always
#    ports:
#      - "2181:2181"
#    volumes:
#      - ./data/zookeeper-volume:/bitnami
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#  kafka:
#    image: docker.io/bitnami/kafka:3.3
#    user: "root:root"
#    restart: always
#    ports:
#      - "9093:9093"
#    volumes:
#      - ./data/kafka-volume:/bitnami
#      - /tmp/offsets:/tmp/offsets
#    environment:
#      - KAFKA_BROKER_ID=1
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
#      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
#      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
#      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
#    depends_on:
#      - zookeeper